#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright 2026 Seclave AB
"""Tests for the offline backup reader: the AES core, the key grouping, the
archive decrypt/authenticate path, and the plaintext exporters.
Run: python3 dev/test_backup.py

The golden archive (golden_backup.bkp) was generated by the Seclave firmware
itself, run in its simulator with the same crypto code the device runs, so
these tests check our reader against the real thing, not against itself. Its backup key is GOLDEN_KEY
below; the simulator's RNG is seeded with zeros, which makes the archive
reproducible. It holds three entries:

    aws-root / work    / root              / s3cr3t-root / prod account
    github   / work    / alice             / octocat!    / 2fa on
    gmail    / persona / alice@example.com / hunter2     / notes

("persona": the generator truncates the group "personal" to the field's
7 usable characters when populating the store; the archive faithfully holds
what the store held.)
"""

import io
import os
import csv
import sys
import json
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))   # the shipped file

import seclave_companion as sc

GOLDEN_KEY = bytes.fromhex("c24c6d83e5bdbf999dda1fe0e90a5d02")
GOLDEN_ENTRIES = [
    {"label": "aws-root", "group": "work", "username": "root",
     "password": "s3cr3t-root", "optional": "prod account"},
    {"label": "github", "group": "work", "username": "alice",
     "password": "octocat!", "optional": "2fa on"},
    {"label": "gmail", "group": "persona", "username": "alice@example.com",
     "password": "hunter2", "optional": "notes"},
]


def golden_archive():
    with open(os.path.join(HERE, "golden_backup.bkp"), "rb") as fh:
        return fh.read()


class AesTests(unittest.TestCase):
    def test_firmware_self_test_vector(self):
        key = bytes([0x00, 0x01, 0x02, 0x03, 0x05, 0x06, 0x07, 0x08,
                     0x0A, 0x0B, 0x0C, 0x0D, 0x0F, 0x10, 0x11, 0x12])
        plain = bytes.fromhex("506812A45F08C889B97F5980038B8359")
        cipher = bytes.fromhex("D8F532538289EF7D06B506A4FD5BE9C9")
        keys = sc.aes_expand_key(key)
        self.assertEqual(sc.aes_encrypt_block(keys, plain), cipher)
        self.assertEqual(sc.aes_decrypt_block(keys, cipher), plain)

    def test_fips197_vector(self):
        keys = sc.aes_expand_key(bytes.fromhex(
            "2b7e151628aed2a6abf7158809cf4f3c"))
        self.assertEqual(
            sc.aes_encrypt_block(keys, bytes.fromhex(
                "3243f6a8885a308d313198a2e0370734")),
            bytes.fromhex("3925841d02dc09fbdc118597196a0b32"))

    def test_decrypt_inverts_encrypt(self):
        keys = sc.aes_expand_key(bytes(range(16)))
        for block in (bytes(16), bytes(range(16)), b"\xff" * 16):
            self.assertEqual(
                sc.aes_decrypt_block(keys, sc.aes_encrypt_block(keys, block)),
                block)


class KeyFormatTests(unittest.TestCase):
    DIGITS = "C24C6D83E5BDBF999DDA1FE0E90A5D02"

    def test_parse_accepts_every_grouping(self):
        for text in (self.DIGITS,
                     self.DIGITS.lower(),
                     "C24C6D83-E5BDBF99-9DDA1FE0-E90A5D02",
                     "C24C6D83 E5BDBF99 9DDA1FE0 E90A5D02"):
            self.assertEqual(sc.parse_backup_key(text), GOLDEN_KEY)

    def test_parse_rejects_wrong_shapes(self):
        for text in ("", self.DIGITS[:-1], self.DIGITS + "0",
                     self.DIGITS[:-1] + "G", "hello"):
            self.assertIsNone(sc.parse_backup_key(text))

    def test_format_groups_by_eight(self):
        self.assertEqual(sc.format_backup_key(self.DIGITS.lower()),
                         "C24C6D83-E5BDBF99-9DDA1FE0-E90A5D02")

    def test_format_while_typing(self):
        # Partial input groups as far as it goes; junk vanishes.
        self.assertEqual(sc.format_backup_key("c24c6d83e5"),
                         "C24C6D83-E5")
        self.assertEqual(sc.format_backup_key("xyz c2-4c"), "C24C")

    def test_format_is_idempotent(self):
        formatted = sc.format_backup_key(self.DIGITS)
        self.assertEqual(sc.format_backup_key(formatted), formatted)

    def test_format_feeds_parse(self):
        self.assertEqual(
            sc.parse_backup_key(sc.format_backup_key(self.DIGITS)),
            GOLDEN_KEY)


class GoldenArchiveTests(unittest.TestCase):
    """The reader against an archive the firmware itself encrypted."""

    def test_decodes_the_firmware_archive(self):
        entries = sc.read_backup_archive(golden_archive(), GOLDEN_KEY)
        self.assertEqual(entries, GOLDEN_ENTRIES)

    def test_wrong_key_is_a_key_error(self):
        with self.assertRaises(sc.BackupKeyError):
            sc.read_backup_archive(golden_archive(), bytes(16))

    def test_one_bit_of_key_matters(self):
        wrong = bytes([GOLDEN_KEY[0] ^ 1]) + GOLDEN_KEY[1:]
        with self.assertRaises(sc.BackupKeyError):
            sc.read_backup_archive(golden_archive(), wrong)

    def test_tampered_record_fails_to_authenticate(self):
        data = bytearray(golden_archive())
        data[10] ^= 1   # inside record 0's ciphertext
        with self.assertRaises(sc.BackupKeyError):
            sc.read_backup_archive(bytes(data), GOLDEN_KEY)

    def test_slot_order_is_immaterial(self):
        # A slot carries its own index, and the MAC authenticates it via the
        # IV: swapping two whole slots still opens, with the entries placed
        # by their indices - the same tolerance the firmware's restore has.
        data = bytearray(golden_archive())
        size = sc.BACKUP_SLOT_SIZE
        data[0:size], data[size:2 * size] = \
            data[size:2 * size], data[0:size]
        self.assertEqual(sc.read_backup_archive(bytes(data), GOLDEN_KEY),
                         GOLDEN_ENTRIES)

    def test_forged_index_fails_to_authenticate(self):
        # The index is plaintext but not malleable: it derives the IV the
        # MAC is computed over.
        data = bytearray(golden_archive())
        data[218] ^= 1   # slot 0's index, low byte
        with self.assertRaises(sc.BackupKeyError):
            sc.read_backup_archive(bytes(data), GOLDEN_KEY)

    def test_duplicated_record_is_a_file_error(self):
        # Slot 1 copied wholesale over slot 0: both authenticate, both claim
        # index 1 - the repeat must be refused, as the firmware refuses it.
        data = bytearray(golden_archive())
        size = sc.BACKUP_SLOT_SIZE
        data[0:size] = data[size:2 * size]
        with self.assertRaises(sc.BackupFileError):
            sc.read_backup_archive(bytes(data), GOLDEN_KEY)

    def test_truncated_file_is_a_file_error(self):
        with self.assertRaises(sc.BackupFileError):
            sc.read_backup_archive(golden_archive()[:-1], GOLDEN_KEY)

    def test_not_an_archive_is_a_file_error(self):
        junk = bytes(sc.BACKUP_SLOT_SIZE * sc.BACKUP_ITEMS)
        with self.assertRaises(sc.BackupFileError):
            sc.read_backup_archive(junk, GOLDEN_KEY)

    def test_legacy_archive_is_named_as_such(self):
        # A first-generation archive is recognized by its cookie family and
        # refused with an explanation, not a generic failure.
        data = bytearray(golden_archive())
        header_cookie = sc.MAX_ENTRIES * sc.BACKUP_SLOT_SIZE + 220
        data[header_cookie:header_cookie + 4] = b"\x08\xf2\x23\x00"
        with self.assertRaises(sc.BackupFileError) as ctx:
            sc.read_backup_archive(bytes(data), GOLDEN_KEY)
        self.assertIn("first-generation", str(ctx.exception))

    def test_dirty_slot_tail_is_a_file_error(self):
        # The device's own restore demands the zero tail of every slot.
        data = bytearray(golden_archive())
        data[sc.BACKUP_BLOB_SIZE] = 1   # first byte of slot 0's padding
        with self.assertRaises(sc.BackupFileError):
            sc.read_backup_archive(bytes(data), GOLDEN_KEY)


class ExportTests(unittest.TestCase):
    ENTRIES = GOLDEN_ENTRIES + [
        {"label": "tricky", "group": "", "username": "tab\there",
         "password": 'q"uo\\te', "optional": "line\nbreak"},
    ]

    def test_json_round_trips(self):
        decoded = json.loads(sc.entries_to_json(self.ENTRIES))
        self.assertEqual(decoded, [dict(e) for e in self.ENTRIES])

    def test_csv_round_trips(self):
        rows = list(csv.reader(io.StringIO(sc.entries_to_csv(self.ENTRIES))))
        self.assertEqual(rows[0], list(sc.EXPORT_FIELDS))
        for row, entry in zip(rows[1:], self.ENTRIES):
            self.assertEqual(row, [entry[k] for k in sc.EXPORT_FIELDS])

    def test_yaml_shape_and_escapes(self):
        text = sc.entries_to_yaml(self.ENTRIES)
        lines = text.splitlines()
        # One mapping per entry, every field present, every scalar quoted.
        self.assertEqual(len(lines), len(self.ENTRIES) * len(sc.EXPORT_FIELDS))
        self.assertEqual(sum(1 for l in lines if l.startswith("- ")),
                         len(self.ENTRIES))
        self.assertIn('- label: "aws-root"', lines)
        self.assertIn('  username: "tab\\there"', lines)
        self.assertIn('  password: "q\\"uo\\\\te"', lines)
        self.assertIn('  optional: "line\\nbreak"', lines)
        # No raw control characters survive into the file.
        self.assertNotIn("\t", text)

    def test_yaml_parses_if_a_parser_is_around(self):
        # PyYAML is not a dependency; when the dev box happens to have it,
        # prove the hand-emitted document loads back exactly.
        try:
            import yaml
        except ImportError:
            self.skipTest("PyYAML not installed")
        decoded = yaml.safe_load(sc.entries_to_yaml(self.ENTRIES))
        self.assertEqual(decoded, [dict(e) for e in self.ENTRIES])

    def test_empty_exports(self):
        self.assertEqual(json.loads(sc.entries_to_json([])), [])
        self.assertEqual(sc.entries_to_yaml([]), "[]\n")
        rows = list(csv.reader(io.StringIO(sc.entries_to_csv([]))))
        self.assertEqual(rows, [list(sc.EXPORT_FIELDS)])

    def test_default_backup_filename_is_dated(self):
        import re
        import time
        name = sc.default_backup_filename()
        self.assertRegex(name, r"^seclave_\d{4}_\d{2}_\d{2}\.bkp$")
        self.assertEqual(name, time.strftime("seclave_%Y_%m_%d.bkp"))


if __name__ == "__main__":
    unittest.main(verbosity=2)
