#!/usr/bin/env python3
"""Generate the Windows version resource from VERSION in seclave_companion.py.

PyInstaller wants the resource as a file (the spec's version= and the one-file
builds' --version-file), and its numbers have to match the app or the exe
misreports itself in Explorer and in Programs and Features. Generating the
file keeps VERSION the single place a release bump is typed: the installer in
turn reads its version back out of the built exe, so nothing else is stamped
by hand.

Run standalone to write the default location, or pass an output path:

    python packaging/windows/make_version_info.py [outfile]
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
APP = os.path.join(ROOT, "seclave_companion.py")
DEFAULT_OUT = os.path.join(ROOT, "build", "version_info.txt")

TEMPLATE = """\
# UTF-8
# Generated by packaging/windows/make_version_info.py - do not edit.
# Stamped from VERSION in seclave_companion.py.

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=%(numbers)s,
    prodvers=%(numbers)s,
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'Seclave AB'),
        StringStruct('FileDescription', 'Seclave Companion'),
        StringStruct('FileVersion', '%(version)s'),
        StringStruct('InternalName', 'SeclaveCompanion'),
        StringStruct('LegalCopyright', 'Copyright 2026 Seclave AB. MIT License.'),
        StringStruct('OriginalFilename', 'SeclaveCompanion.exe'),
        StringStruct('ProductName', 'Seclave Companion'),
        StringStruct('ProductVersion', '%(version)s'),
      ]),
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def app_version():
    """Read VERSION out of the app without importing it (needs no Tk)."""
    with open(APP, encoding="utf-8") as f:
        match = re.search(r'^VERSION = "([^"]+)"', f.read(), re.M)
    if not match:
        raise SystemExit("no VERSION in %s" % APP)
    return match.group(1)


def write_version_info(out=DEFAULT_OUT):
    """Write the resource file and return its path."""
    version = app_version()
    # The fixed-info fields are four 16-bit numbers, so a version like "1.1.2"
    # pads to (1, 1, 2, 0). Any non-numeric suffix is dropped there but kept in
    # the strings Explorer shows.
    parts = [int(p) for p in re.findall(r"\d+", version)[:4]]
    parts += [0] * (4 - len(parts))
    directory = os.path.dirname(out)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(TEMPLATE % {"numbers": tuple(parts), "version": version})
    return out


if __name__ == "__main__":
    print(write_version_info(*sys.argv[1:2]))
